CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_GLIBCXX_LIBCPP=y

CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_MODE_DEFERRED=y

# ===== USB 新版设备栈 =====
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y

# ===== 串口和控制台 =====
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UDC_RPI_PICO=y
# ===== 禁用 CDC-ACM 的日志警告 =====
CONFIG_USBD_CDC_ACM_LOG_LEVEL_DBG=n
CONFIG_USBD_CDC_ACM_LOG_LEVEL_INF=n
CONFIG_USBD_CDC_ACM_LOG_LEVEL_WRN=n
CONFIG_USBD_CDC_ACM_LOG_LEVEL_ERR=y

# ===== 临时禁用 -Werror =====
CONFIG_COMPILER_WARNINGS_AS_ERRORS=n

CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y 